[tool.poetry]
name = "fastapidemo"
version = "0.1.0"
description = ""
authors = ["sandboa <bsse0807@iit.du.ac.bd>"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
